[package]
name = "prjunnamed-yosys_json"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
prjunnamed-netlist.workspace = true
jzon.workspace = true
