on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
    - name: Set up toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Set up Z3
      uses: cda-tum/setup-z3@v1
    - name: Run tests
      run: cargo test
    - name: Run tests and verify with SMT
      run: cargo test --features verify -p prjunnamed-generic
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        # Must bump above the default of 1.71.0 to accept edition 2024.
        # Kept below 1.85.0 to work around https://github.com/EmbarkStudios/cargo-deny/issues/741
        rust-version: 1.84
